### ISSUE TITLE
Consider migrating to maven repository

### ISSUE THREAD

**Issue by yamin8000** [SkybirdBits/PersianDatePicker#2]
Since JitPack is not secure enough and most JVM/Android libs are published using maven repository, consider publishing your library in MVN for future releases.
Publishing your library in MVN may be a difficult task but it's worth it.
More info:
https://proandroiddev.com/publishing-your-first-android-library-to-mavencentral-be2c51330b88
https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/
https://github.com/vanniktech/gradle-maven-publish-plugin

**Comment by SkybirdBits** [comment]
I don't know why you tell about the security but yep you are right maven repository is a standard way
